/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-105054-gd6b2357edd-20220102"
#endif /* AVUTIL_FFVERSION_H */
